### ISSUE TITLE
Problem with GOG version?

### ISSUE THREAD

**Issue by GhostofaMessiah** [jdsmith2816/tw3mw#10]
[Wabbajack.current.log](https://github.com/jdsmith2816/tw3mw/files/9386290/Wabbajack.current.log)

Fails after 472/472 on step 8.

**Comment by HighwaymanEd** [comment]
It's noted in the readme that it only works with the Steam Edition. Damned shame as I have to buy it in Steam to get it to work as well, so waiting for a suitable sale :(

**Comment by Rustynails07** [comment]
I've tried this modlist using both the GOG and Steam versions of the GOTY edition, each time receiving the same lines of code:

(Retry 1 of 5), got exception (2) The system cannot find the file specified: etc

I see the modlist is currently under maintenance. Has anyone come across a fix or something I'm doing wrong? Thanks!

**Comment by jdsmith2816** [comment]
The modlist is not under maintenance and it requires every DLC to be purchased and installed via steam.  If you have ALLL the DLC it _will_ work.

Here's the full list..

https://cdn.discordapp.com/attachments/989620864809062450/1012137991952674917/unknown.png
