### ISSUE TITLE
cant install mega files

### ISSUE THREAD

**Issue by sushiboyy** [jdsmith2816/tw3mw#2]
when the install is almost finished, a few files that are downloaded via mega and media fire which states they cant be hashed. if you could post a link to these files that would be great!.

![Screenshot (1)](https://user-images.githubusercontent.com/109486985/179426883-0c0eb1a6-48ba-4d6e-bd86-ea272508d0e3.png)

**Comment by sushiboyy** [comment]
while replying to your comment the downloads actually worked lmao. thank you for the reply, and now i have to wait for the archives to finish being extracted :(

**Comment by jdsmith2816** [comment]
Glad you made progress!  I hope you have a great time with the list. :)
