### ISSUE TITLE
Russain Localization

### ISSUE THREAD

**Issue by Yeribeon** [jdsmith2816/tw3mw#3]
**Describe the bug**
I can't turn on the Russian localization. There is no switch in in-game settings, and when I manually change the entire localization section in user.settings, the speech language reverts back to english.

**Comment by sushiboyy** [comment]
did you install the mod list without any installation errors? when i tried to install it, wabbajack couldn't download the mega files.

**Comment by Yeribeon** [comment]
> did you install the mod list without any installation errors? when i tried to install it, wabbajack couldn't download the mega files.

Well, I ran the installation two times. First time there were some missing files, but there were no missing files second time. I just cant change the localization to Russian.

**Comment by jdsmith2816** [comment]
Sorry mate, I have no idea what might be going on with the localization switch.  I only know how the english version works also there are changes made to the menus and such that were only made i the english localization files.  This may or may not cause you issues?
