### ISSUE TITLE
Gamepad issue

### ISSUE THREAD

**Issue by NoobModder123** [jdsmith2816/tw3mw#5]
Love the modlist, i first played it on console years ago and this list made me come back to it on pc.

I currently play with the xbox gamepad and have been experiencing problems with quen. 

It seems from the starting tutorial there isn't a dedicated cast button on gamepad. My aim is to use square/X or leftshoulder as a cast button and remove the quick cast system that uses the left trigger. 

I tried messing around with the inputfile in the profiles folder to no avail. Hope you can help me out!

**Comment by jdsmith2816** [comment]
@NoobModder123 I hope you figured things out.  If not the gamepad controls are pinned in the discord server but I'll paste them below.

```md
# Gamepad Controls

## Exploration
L2 - Toggle Witcher Senses / Use Signs
L3 - Toggle Night Sight
L3 (Hold) - Open Essentials Panel
L3 + L3 - Call Roach
R3 (Hold 0.5) - Meditate
Y - Quick Access
A - Sprint
B - Jump
Select - Open Main Menu
Select (Hold 0.5) - Open Inventory Panel
Select (Hold 1.2) - Open Glossary Panel
Start - Open Menu
Start (Hold 0.5) - Open Map Panel

## Swimming
R1 - Surface
R2 - Dive

## Combat
L1 - Throw Item / Shoot Crossbow
L2 - Parry / Use Signs
R3 - Lock Target
RB - Light Attack
RT - Heavy Attack
A - Combat Roll
B - Dodge

Jump while in combat: Start sprinting first, then press B

## Signs
L2 + L1 - Igni (Tap for Instant Cast / Hold for alternate)
L2 + X - Aard (Tap for Instant Cast / Hold for alternate)
L2 + Y - Yrden (Tap for Instant Cast / Hold for alternate)
L2 + B - Quen (Tap for Instant Cast / Hold for alternate)
L2 + A - Axii (Tap for Instant Cast / Hold for alternate)
```
